---
jobs:
  molecule:
    machine:
      image: ubuntu-1604:202004-01
    parameters:
      python-version:
        type: string
      distro:
        type: string
    steps:
      - checkout:
          path: cowsay
      - run:
          name: "Show avairale python version"
          command: pyenv install --list
      - run:
          name: Upate pyenv
          command: |
            git clone https://github.com/pyenv/pyenv-update.git $(pyenv root)/plugins/pyenv-update
            pyenv update
      - run:
          name: Install Python
          command: pyenv install << parameters.python-version>>
      - run:
          name: "Show avairale python version"
          command: pyenv install --list
      - run:
          name: "Set Python Version"
          command: pyenv global << parameters.python-version >>
      - run:
          name: Install Molecule and dependencies
          command: |
            cd cowsay
            pip install -r molecule/requirements.txt
      - run:
          name: Test with Molecule
          command: |
            cd cowsay
            molecule test
          environment:
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
            MOLECULE_DISTRO: << parameters.distro >>

version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - molecule:
          matrix:
            parameters:
              python-version: ['3.6.11', '3.7.8', '3.8.3']
              distro: ['centos7', 'centos8']
