---
roles:
  - name: mamono210.postgresql
    src: https://github.com/ansible-roles-mamono210/postgresql.git
  - name: mamono210.molecule_ec2_driver
    src: https://github.com/ansible-roles-mamono210/molecule_ec2_driver.git
