---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether cowsay is installed
      ansible.builtin.command: cowsay hello
      register: COWSAY_INSTALLED
      changed_when: False
      ignore_errors: True

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: False

    - name: Show cowsay is installed
      ansible.builtin.debug:
        var: COWSAY_INSTALLED

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
